### ISSUE TITLE
Supervisor Error

### ISSUE THREAD

**Issue by CokkocZateki** [shibdib/Dramiel#4]
hey

I get this error from my supervisor log and not sure how to proceed from here

2016-07-08 22:03:41,343 INFO RPC interface 'supervisor' initialized
2016-07-08 22:03:41,343 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-07-08 22:03:41,344 INFO daemonizing the supervisord process
2016-07-08 22:03:41,344 INFO supervisord started with pid 511
2016-07-08 22:07:29,173 INFO spawned: 'dramiel' with pid 680
2016-07-08 22:07:29,221 INFO exited: dramiel (exit status 1; not expected)
2016-07-08 22:07:30,223 INFO spawned: 'dramiel' with pid 681
2016-07-08 22:07:30,260 INFO exited: dramiel (exit status 1; not expected)
2016-07-08 22:07:32,264 INFO spawned: 'dramiel' with pid 682
2016-07-08 22:07:32,310 INFO exited: dramiel (exit status 1; not expected)
2016-07-08 22:07:35,314 INFO spawned: 'dramiel' with pid 685
2016-07-08 22:07:35,353 INFO exited: dramiel (exit status 1; not expected)
2016-07-08 22:07:36,354 INFO gave up: dramiel entered FATAL state, too many start retries too quickly
2016-07-08 22:47:23,546 INFO spawned: 'dramiel' with pid 1639
2016-07-08 22:47:23,602 INFO exited: dramiel (exit status 1; not expected)
2016-07-08 22:47:24,604 INFO spawned: 'dramiel' with pid 1640
2016-07-08 22:47:24,673 INFO exited: dramiel (exit status 1; not expected)
2016-07-08 22:47:26,678 INFO spawned: 'dramiel' with pid 1641
2016-07-08 22:47:26,725 INFO exited: dramiel (exit status 1; not expected)
2016-07-08 22:47:29,730 INFO spawned: 'dramiel' with pid 1646
2016-07-08 22:47:29,771 INFO exited: dramiel (exit status 1; not expected)
2016-07-08 22:47:30,772 INFO gave up: dramiel entered FATAL state, too many start retries too quickly

i added the below into dramiel.conf so not sure where i went wrong

`[program:dramiel]    
command=php /directory to your bot folder/Dramiel/Dramiel.php    
autostart=true    
autorestart=true   
stopasgroup=true    
stderr_logfile=/directory to your bot folder/Dramiel/log/dramielError.log
stdout_logfile=/directory to your bot folder/Dramiel/log/dramielOther.log
stdout_logfile_maxbytes=100KB
stdout_logfile_backups=3
stderr_logfile_maxbytes=100KB
stderr_logfile_backups=3
priority=998`

**Comment by shibdib** [comment]
directory to your bot folder

You need to fill that part out

**Comment by CokkocZateki** [comment]
i did. ive added all the channel ids and api keys etc.

**Comment by CokkocZateki** [comment]
hmm i get the below error 

googled it but nothing works

`supervisorctl restart
error: <class 'xmlrpclib.Fault'>, <Fault 6: 'SHUTDOWN_STATE'>: file: /usr/lib/python2.7/xmlrpclib.py line: 794
`

**Comment by shibdib** [comment]
can you screenshot or copy paste ur actual .conf file

**Comment by CokkocZateki** [comment]
updating the issue.

i cleared the database and restarted supervisor. 

then get error

#0 /home/Dramiel/src/lib/Db.php(116): PDO->prepare('SELECT solarSys...')
#1 /home/Dramiel/src/plugins/onMessage/price.php(65): dbQuery('SELECT solarSys...', Array, 'ccp')
#2 /home/Dramiel/Dramiel.php(119): price->init(Array, Object(Discord\Discord), Object(Monolog\Logger))
#3 {main}
  thrown in /home/Dramiel/src/lib/Db.php on line 116

**Comment by CokkocZateki** [comment]
and the last error 

PHP Catchable fatal error:  Argument 1 passed to Discord\Discord::__construct() must be of the type array, string given, called in /home/Dramiel/Dramiel.php on line 82 and defined in /home/Dramiel/vendor/team-reflex/discord-php/src/Discord/Discord.php on line 282

**Comment by shibdib** [comment]
I'm having trouble reproducing this. I'm guessing it's an issue in the config where you put ur token for the bot but like I said, having trouble reproducing

**Comment by shibdib** [comment]
Got my install to do that, working on a fix now

**Comment by CokkocZateki** [comment]
Okay perfect. Was it the token causing the error?

**Comment by shibdib** [comment]
fixed

**Comment by CokkocZateki** [comment]
sorry still getting errors 

`PHP Fatal error:  Class 'Discord\WebSockets\WebSocket' not found in /home/Dramiel/Dramiel.php on line 120`

https://postimg.org/image/6piml7cwn/

showing line 120 and no idea why its doing that. @shibdib 

ive git pulled. git checkout to ensure that the Dramiel.php is correct as per master
